name: NodeJS

on:
  push:
    branches: [ "bestiary" ]
  pull_request:
    branches: [ "bestiary" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
    
    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: Install ionic
      run: npm install -g @ionic/cli

    - name: Build     
      run: |
        npm install
        ionic build --prod
        npx cap sync
        
    - name: Archive production artifacts
      uses: actions/upload-artifact@v3
      with:
        name: www
        path: www
     
    #- name: Build Signed APK
    #  uses: victorbnl/build-signed-apk@main
    #  with:
    #    gradlew_file: android/gradlew
    #    gradlew_dir: android/
    #    keystore_file: android.jks
    #    keystore_password: ${{ secrets.KEYSTORE_PASS }}
    #    key_alias: ${{ secrets.KEY_ALIAS }}
    #    key_password: ${{ secrets.KEY_PASSWORD }}
        
    #- name: Copy file
    #  uses: canastro/copy-action@0.0.2
    #  with:
    #    source: app/build/outputs/apk/release/app-release.apk
    #    target: www/falloutjdrhelper.apk
          
    - name: SFTP Deploy
      uses: wlixcc/SFTP-Deploy-Action@v1.2.2
      with:
        username: kyne
        server: kyne.ovh
        ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
        local_path: ./www/*
        remote_path: /home/kyne/fallout-test-www
        
        
