name: NodeJS

on:
  push:
    branches: [ "bestiary" ]
  pull_request:
    branches: [ "bestiary" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
    
    steps:
    - uses: actions/checkout@v3
      with:
          fetch-depth: 0
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: Install ionic
      run: npm install -g @ionic/cli

    - name: Build     
      run: |
        npm install
        ionic build --prod
        npx cap sync
        
    #- name: Archive production artifacts
    #  uses: actions/upload-artifact@v3
    #  with:
    #    name: www
    #    path: www
     
    #- name: SFTP Deploy
    #  uses: wlixcc/SFTP-Deploy-Action@v1.2.2
     # with:
    #    username: kyne
    #    server: kyne.ovh
     #   ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
   #     local_path: ./www/*
    #   remote_path: /home/kyne/fallout-test-www

    - name: "Deploy"
      uses: milanmk/actions-file-deployer@master
      with:
          remote-protocol: "sftp"
          remote-host: "kyne.ovh"
          remote-user: "kyne"
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          local-path: ./www/
          remote-path: /home/kyne/fallout-test-www
        
